services:
  db:
    image: postgres:15
    container_name: mergetune_db
    restart: always
    environment:
      - DJANGO_DB_HOST=mergetune_db
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    container_name: backend_mergetune
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: api.settings
    stdin_open: true
    tty: true

volumes:
  postgres_data:
