services:
  db:
    image: postgres:15
    container_name: mergetune_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    container_name: backend_mergetune
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: api.settings
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
    stdin_open: true
    tty: true

volumes:
  postgres_data:
